name: LaunchQQ

on:
  push:
    paths:
      - 'LaunchQQ.py'
      - '.github/workflows/launcher.yml'
  pull_request:
    paths:
      - 'LaunchQQ.py'
      - '.github/workflows/launcher.yml'
  workflow_dispatch:

jobs:
  install_test_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9  # 指定 Python 3 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pyinstaller & Build LaunchQQ.exe
      run: |
        python -m pip install pyinstaller
        pyinstaller --onefile --uac-admin LaunchQQ.py -n LaunchQQ

    - name: Upload install_windows_pyinstaller.exe
      uses: actions/upload-artifact@v4
      with:
        name: LaunchQQ
        path: dist/LaunchQQ.exe
